### ISSUE TITLE
Credentials expiry is broken

### ISSUE THREAD

**Issue by KlausVii** [openfga/js-sdk#26]
### Description

When using `ClientCredentials` for auth, the token is not cached properly because the `expires_in` amount is treated as milliseconds instead of seconds

### Version of SDK

0.2.6

### Version of OpenFGA (if known)

N/A

### Reproduction

Run the client with `ClientCredentials` enabled and observe how many requests are made to your auth token service.

The issue is (here)[https://github.com/openfga/js-sdk/blob/main/credentials/credentials.ts#L155]
```
this.accessTokenExpiryDate = new Date(Date.now() + response.data.expires_in);
```
[Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) returns the time in milliseconds, [expires_in](https://www.rfc-editor.org/rfc/rfc6749#section-5.1) is in seconds -> the expiry gets set 1000 times too soon!

### Expected behavior

I do not DDOS my auth service because of openFGA

### Additional context
> Add any other context about the problem here.

**Comment by VeskoPavlov** [comment]
We would really appreciate having a prompt review of the PR, since at the moment we are sending thousands of request to our authentication server and risk being blocked. At the same time we cannot disable authentication as it imposed a security risk. Also, the change is really minimal.
Thank you in advance!

**Comment by rhamzeh** [comment]
@KlausVii @VeskoPavlov [`v0.2.7`](https://www.npmjs.com/package/@openfga/sdk) is out with the fix. Thanks for reporting and the contribution!

**Comment by KlausVii** [comment]
Thanks for the quick turnaround
