### ISSUE TITLE
Including js-sdk version in request headers

### ISSUE THREAD

**Issue by ragaeeb** [openfga/js-sdk#9]
👋 hello! I would like to request that the OpenFGA js-sdk version is included in the request headers. This will allow us to properly route the requests to the right OpenFGA server based on the sdk-version (if there are breaking changes) using load balancers.

**Comment by rhamzeh** [comment]
Hey @ragaeeb 

The SDK should already be sending the header, provided it is not used from a browser context, or not initialized with an overriding User-Agent.

The `User-Agent` header will be of the form: `openfga-sdk js/x.y.z`, where `x.y.z` is the SDK version.

On the latest JS SDK at the time of this comment, this should be: `openfga-sdk js/0.2.2`

See here: https://github.com/openfga/js-sdk/blob/main/configuration.ts#L151

**Comment by ragaeeb** [comment]
Excellent! Thank you @rhamzeh! Closing this issue
